framework:
    asset_mapper:
        paths:
            - assets/
            - vendor/easycorp/easyadmin-bundle/assets/
        missing_import_mode: warn

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
