[variables]
NIXPACKS_PHP_EXTENSIONS = 'pdo,pdo_mysql,intl,ctype,iconv,mbstring,zip'

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-scripts']

[phases.build]
cmds = ['php bin/console cache:clear --no-warmup']

[start]
cmd = 'php -S 0.0.0.0:${PORT:-8080} -t public'
